service: bcshopkeeper

frameworkVersion: "2"

custom:
  dotenvVars: ${file(configs.js)}

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  environment: ${file(configs.js)}
  profile: bcshopkeeper

functions:
  shopkeeper:
    handler: handler.shopkeeper
    events:
      - schedule: rate(15 minutes)
    environment:
      BOT: ${env:BOT}
      CH: ${env:CH}
      URL: ${env:URL}
